name: P3-Workflow

on: [push, pull_request, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile P3
        run: |
          javac -cp "src/" ../../Projects/P3/src/*.java
          javac -cp "tests/" ../../Projects/P3/tests/*.java
          javac -cp "junit-4.10.jar:." *.java
